// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    AppButton: typeof import('./src/modules/ui/components/app/buttons/app-button/AppButton.vue')['default']
    'AppButton.story': typeof import('./src/modules/ui/components/app/buttons/app-button/AppButton.story.vue')['default']
    AppConfirmButton: typeof import('./src/modules/ui/components/app/buttons/app-confirm-button/AppConfirmButton.vue')['default']
    'AppConfirmButton.story': typeof import('./src/modules/ui/components/app/buttons/app-confirm-button/AppConfirmButton.story.vue')['default']
    AppDropdownButton: typeof import('./src/modules/ui/components/app/buttons/app-dropdown-button/AppDropdownButton.vue')['default']
    'AppDropdownButton.story': typeof import('./src/modules/ui/components/app/buttons/app-dropdown-button/AppDropdownButton.story.vue')['default']
    AppDropdownButtonItem: typeof import('./src/modules/ui/components/app/buttons/app-dropdown-button/AppDropdownButtonItem.vue')['default']
    AppIconButton: typeof import('./src/modules/ui/components/app/buttons/app-icon-button/AppIconButton.vue')['default']
    'AppIconButton.story': typeof import('./src/modules/ui/components/app/buttons/app-icon-button/AppIconButton.story.vue')['default']
    AppLoader: typeof import('./src/modules/ui/components/app/loaders/AppLoader.vue')['default']
    'AppLoader.story': typeof import('./src/modules/ui/components/app/loaders/AppLoader.story.vue')['default']
    AppModal: typeof import('./src/modules/ui/components/app/modals/AppModal.vue')['default']
    'AppModal.story': typeof import('./src/modules/ui/components/app/modals/AppModal.story.vue')['default']
    ArrowDownIcon: typeof import('./src/components/icons/ArrowDownIcon.vue')['default']
    CheckmarkIcon: typeof import('./src/components/icons/CheckmarkIcon.vue')['default']
    ChevronDownIcon: typeof import('./src/components/icons/ChevronDownIcon.vue')['default']
    ChevronRightIcon: typeof import('./src/components/icons/ChevronRightIcon.vue')['default']
    CloseIcon: typeof import('./src/components/icons/CloseIcon.vue')['default']
    EditIcon: typeof import('./src/components/icons/EditIcon.vue')['default']
    FormInputField: typeof import('./src/modules/ui/components/forms/field/FormInputField.vue')['default']
    'FormInputField.story': typeof import('./src/modules/ui/components/forms/field/FormInputField.story.vue')['default']
    FormInputGroup: typeof import('./src/modules/ui/components/forms/group/FormInputGroup.vue')['default']
    FormLabel: typeof import('./src/modules/ui/components/forms/label/FormLabel.vue')['default']
    FormSelect: typeof import('./src/modules/ui/components/forms/select/FormSelect.vue')['default']
    'FormSelect.story': typeof import('./src/modules/ui/components/forms/select/FormSelect.story.vue')['default']
    FormSelectInput: typeof import('./src/modules/ui/components/forms/select/FormSelectInput.vue')['default']
    FormSelectOption: typeof import('./src/modules/ui/components/forms/select/FormSelectOption.vue')['default']
    FormSlider: typeof import('./src/modules/ui/components/forms/slider/FormSlider.vue')['default']
    'FormSlider.story': typeof import('./src/modules/ui/components/forms/slider/FormSlider.story.vue')['default']
    InfoIcon: typeof import('./src/components/icons/InfoIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    SettingsIcon: typeof import('./src/components/icons/SettingsIcon.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    TransitionExpand: typeof import('./src/modules/ui/components/transitions/TransitionExpand.vue')['default']
    TrashIcon: typeof import('./src/components/icons/TrashIcon.vue')['default']
    WarningIcon: typeof import('./src/components/icons/WarningIcon.vue')['default']
  }
}
